AllCops:
  Include:
    - tasks/*.rake
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - db/schema.rb

LineLength:
  Max: 100

MethodLength:
  Max: 20

CyclomaticComplexity:
  Max: 8

Documentation:
  Enabled: false
